<!-- footer template originally from sw. modified slightly for rawk. -->
<div id="footer">
<div class="right">generated by 
<a href="https://github.com/kisom/">rawk</a> and
<a href="http://s01.de/~tox/index.cgi/proj_smu/">smu</a>.
</div>
</body>
</html>

